# alt küme üzerinde işlem yapmak

In [1]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[2, 6, 4, 7, 7],
       [4, 1, 8, 3, 7],
       [1, 9, 0, 2, 9],
       [7, 7, 0, 5, 6],
       [9, 2, 6, 9, 8]])

In [2]:
alt_a = a[0:3,0:2]
alt_a

array([[2, 6],
       [4, 1],
       [1, 9]])

In [4]:
alt_a[0,0] = 99999
alt_a[1,1] = 888
alt_a

array([[99999,     6],
       [    4,   888],
       [    1,     9]])

In [5]:
a

array([[99999,     6,     4,     7,     7],
       [    4,   888,     8,     3,     7],
       [    1,     9,     0,     2,     9],
       [    7,     7,     0,     5,     6],
       [    9,     2,     6,     9,     8]])

In [6]:
# yaptığımız değişiklik a da da meydana geldi ana parçada değişiklik yaptı

In [7]:
#eğer ana array bozmak istemiyorsak;

In [8]:
m = np.random.randint(10, size = (5,5))
m

array([[0, 3, 5, 3, 4],
       [4, 5, 6, 4, 6],
       [1, 7, 6, 6, 8],
       [4, 5, 2, 9, 6],
       [9, 8, 8, 4, 9]])

In [10]:
alt_b = m[0:3,0:2].copy()
alt_b

array([[0, 3],
       [4, 5],
       [1, 7]])

In [11]:
alt_b[0,0] = 9999
alt_b[1,1] = 888
alt_b

array([[9999,    3],
       [   4,  888],
       [   1,    7]])

In [12]:
m

array([[0, 3, 5, 3, 4],
       [4, 5, 6, 4, 6],
       [1, 7, 6, 6, 8],
       [4, 5, 2, 9, 6],
       [9, 8, 8, 4, 9]])

In [13]:
# copy işleminden sonraki işlemler ana arraydan bağımsız olarak gerçekleştirilmiş oldu