# slicing ile elemanlara erişmek ( array alt küme işlemleri)

In [2]:
import numpy as np

In [4]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
a[0:3]

array([20, 21, 22])

In [6]:
a[:3]

array([20, 21, 22])

In [7]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [8]:
a[1::2]

array([21, 23, 25, 27, 29])

In [9]:
a[2::2]

array([22, 24, 26, 28])

In [10]:
#iki boyutlu slice işlemleri


In [11]:
m = np.random.randint(10, size = [5,5])
m

array([[8, 0, 0, 2, 4],
       [8, 9, 1, 2, 6],
       [2, 2, 8, 6, 0],
       [9, 7, 4, 7, 4],
       [5, 2, 9, 7, 8]])

In [12]:
m[:,0]

array([8, 8, 2, 9, 5])

In [13]:
m[:,1]

array([0, 9, 2, 7, 2])

In [14]:
m[:,4]

array([4, 6, 0, 4, 8])

In [15]:
m[0,:]

array([8, 0, 0, 2, 4])

In [16]:
m[0]

array([8, 0, 0, 2, 4])

In [17]:
m[1,:]

array([8, 9, 1, 2, 6])

In [18]:
#hem satır hem sütuna birlikte eriş

In [28]:
m

array([[8, 0, 0, 2, 4],
       [8, 9, 1, 2, 6],
       [2, 2, 8, 6, 0],
       [9, 7, 4, 7, 4],
       [5, 2, 9, 7, 8]])

In [20]:
m[0:2, 0:3]

array([[8, 0, 0],
       [8, 9, 1]])

In [24]:
m[::,:2]

array([[8, 0],
       [8, 9],
       [2, 2],
       [9, 7],
       [5, 2]])

In [25]:
m[:,0:2]

array([[8, 0],
       [8, 9],
       [2, 2],
       [9, 7],
       [5, 2]])

In [27]:
m

array([[8, 0, 0, 2, 4],
       [8, 9, 1, 2, 6],
       [2, 2, 8, 6, 0],
       [9, 7, 4, 7, 4],
       [5, 2, 9, 7, 8]])

In [26]:
m[1:3,0:2]

array([[8, 9],
       [2, 2]])