# array ayırma (splitting)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,99,99,3,2,1])

In [3]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [4]:
a,b,c = np.split(x, [3,5])

In [7]:
a

array([1, 2, 3])

In [8]:
b

array([99, 99])

In [9]:
c

array([3, 2, 1])

In [10]:
#iki boyutlu ayırma


In [12]:
n = np.arange(16).reshape(4,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.vsplit(n, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [15]:
ust, alt = np.vsplit(n, [2])

In [16]:
ust


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
np.hsplit(n, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [20]:
sag, sol = np.hsplit(n, [2])

In [21]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [22]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])