# array sıralama (sorting)

In [1]:
import numpy as np


In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [7]:
v.sort()
v

array([1, 2, 3, 4, 5])

In [8]:
#iki boyutlu array sıralama


In [10]:
a = np.random.normal(20,5, (3,3))

In [11]:
a

array([[20.79717368, 16.87743205, 13.44987607],
       [22.49284386, 22.42434283, 31.39688645],
       [19.68044435, 15.67308456,  9.67344   ]])

In [12]:
np.sort(a, axis = 1)

array([[13.44987607, 16.87743205, 20.79717368],
       [22.42434283, 22.49284386, 31.39688645],
       [ 9.67344   , 15.67308456, 19.68044435]])

In [13]:
np.sort(a, axis = 0)

array([[19.68044435, 15.67308456,  9.67344   ],
       [20.79717368, 16.87743205, 13.44987607],
       [22.49284386, 22.42434283, 31.39688645]])