# array birleştirme (concatenation)

In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [7]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [8]:
z = np.array([7,8,9])

In [9]:
np.concatenate((x,y,z))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#iki boyut

In [11]:
a  = np.array([[1,2,3],
               [4,5,6]])

In [13]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [14]:
np.concatenate([a,a],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])