# fancy index ile elemanlara erişmek

In [1]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [2]:
v[0]

0

In [3]:
v[1]

3

In [4]:
v[3]

9

In [5]:
[v[0],v[1],v[3]]

[0, 3, 9]

In [6]:
# birden çok index olduğunda bu index değerlerini bir kerede sorgulama;

In [10]:
al_getir = [0,1,3]

In [11]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [12]:
v[al_getir]

array([0, 3, 9])

In [13]:
#işte buna fancy index denir

In [14]:
#iki boyutta fancy


In [34]:
n = np.arange(9).reshape((3,3))
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [36]:
n[satir, sutun]

array([1, 5])

In [37]:
#basit index ile fancy index

In [38]:
n[0, [1,2]]

array([1, 2])

In [39]:
#slice ile fancy

In [41]:
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
n[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])