# index ile elemanlara erismek

In [1]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([1, 0, 7, 9, 3, 3, 4, 9, 6, 0])

In [2]:
a[0]

1

In [3]:
a[-1]

0

In [5]:
a[0] = 100
a

array([100,   0,   7,   9,   3,   3,   4,   9,   6,   0])

In [6]:
#iki boyutlu array


In [7]:
n = np.random.randint(10, size = (3,5))
n

array([[0, 2, 3, 6, 8],
       [4, 8, 3, 0, 7],
       [3, 0, 9, 3, 7]])

In [8]:
n[0,0]

0

In [12]:
n[1,1]

8

In [13]:
n[2,2]

9

In [14]:
n[1,3]

0

In [15]:
n[1,3] = 100

In [16]:
n

array([[  0,   2,   3,   6,   8],
       [  4,   8,   3, 100,   7],
       [  3,   0,   9,   3,   7]])

In [17]:
n[1,3] = 2.2
n

array([[0, 2, 3, 6, 8],
       [4, 8, 3, 2, 7],
       [3, 0, 9, 3, 7]])

In [18]:
#ondalık tipi kabul etmedi eğer içinde bir ondalık varsa hepsini ona göre oluşturmus oldu
