# matematiksel işlemler

In [2]:
import numpy as np
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [3]:
v - 1

array([0, 1, 2, 3, 4])

In [4]:
v *3

array([ 3,  6,  9, 12, 15])

In [5]:
v*5/2

array([ 2.5,  5. ,  7.5, 10. , 12.5])

In [6]:
#ufunc: arka tarafta işlemler dönüştürülüyor numpy içinde spesifik fonk çalıştırılıyor

In [40]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [7]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [8]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [10]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [11]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [12]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [13]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [14]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [15]:
v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [16]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [17]:
np.absolute(np.array([-3])) #mutlak değer alma

array([3])

In [18]:
np.sin(360)

0.9589157234143065

In [19]:
np.cos(180)

-0.5984600690578581

In [21]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [22]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [23]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [24]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [25]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\lenovo\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
 

In [26]:
#cheatsheet

# istatistiksel hesaplamalar

In [ ]:
np.mean(arr,axis=0) | Returns mean along specific axis
arr.sum() | Returns sum of arr
arr.min() | Returns minimum value of arr
arr.max(axis=0) | Returns maximum value of specific axis
np.var(arr) | Returns the variance of array
np.std(arr,axis=1) | Returns the standard deviation of specific axis
arr.corrcoef() | Returns correlation coefficient of array

In [28]:
v

array([1, 2, 3])

In [29]:
np.mean(v)

2.0

In [30]:
v.sum()

6

In [31]:
v.min()

1

In [32]:
v.max()

3

In [33]:
np.var(v)

0.6666666666666666

In [34]:
np.std(v)

0.816496580927726

In [36]:
np.std(v, axis=0)

0.816496580927726

In [38]:
np.corrcoef(v)

1.0