#  numpy ile iki bilinmeyenli denklem çözümü

In [1]:
import numpy as np

In [ ]:
5*x0+x1 =12
x0+3*x1 =10

In [3]:
#bilinmeyen ifadelerin katsayılarını bir vektöre koymak 

In [5]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [6]:
a

array([[5, 1],
       [1, 3]])

In [7]:
b

array([12, 10])

In [8]:
x = np.linalg.solve(a,b)
x
#katsayıları hesapla

array([1.85714286, 2.71428571])