# NumPy Array'i Oluşturmak

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [6]:
np.array([3.14,4,2,13] , dtype = "int")

array([ 3,  4,  2, 13])

In [7]:
#sifirdan array olusturma

In [11]:
np.zeros(10 , dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.ones((3,5), dtype ="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [15]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.random.normal(10,4, (3,4))

array([[ 8.02125552, 13.02043861, 17.05677963, 12.15358737],
       [12.85141406, 12.8470583 ,  9.70464627, 12.50692704],
       [ 9.95713577, 15.11230095, 12.72391085,  7.07372621]])

In [19]:
np.random.randint(0,10, (3,3))

array([[4, 0, 9],
       [4, 4, 7],
       [3, 8, 7]])